export const ADD_SHAPE = "ADD_SHAPE";
export const REMOVE_SHAPE = "REMOVE_SHAPE";
export const TRANSFORM_WIDTH_SHAPE = "TRANSFORM_WIDTH_SHAPE";
export const TRANSFORM_HEIGHT_SHAPE = "TRANSFORM_HEIGHT_SHAPE";
export const MOVE_SHAPE_X = "MOVE_SHAPE_X";
export const MOVE_SHAPE_Y = "MOVE_SHAPE_Y";
export const GET_DETAIL_SHAPE = "GET_DETAIL_SHAPE";